server:
  port: ${PORT:8088}

spring:
  application:
    name: gateway-service-austral

  cloud:
    gateway:
      server:
        webflux:
          routes:

server:
  port: ${PORT:8088}

spring:
  application:
    name: gateway-service-austral

  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: auth-service
              uri: ${AUTH_SERVICE_URL:https://authservice-serviceaustral.onrender.com}
              predicates:
                - Path=/api/v1/auth/**

            - id: usuarios-service
              uri: ${USUARIOS_SERVICE_URL:https://usuarios-serviceaustral-1.onrender.com}
              predicates:
                - Path=/api/v1/usuarios/**

            - id: centros-service
              uri: ${CENTROS_SERVICE_URL:https://centros-serviceaustral.onrender.com}
              predicates:
                - Path=/api/v1/centros/**

            - id: jaulas-service
              uri: ${JAULAS_SERVICE_URL:https://jaulas-serviceaustral.onrender.com}
              predicates:
                - Path=/api/v1/jaulas/**

            - id: monitoreo-service
              uri: ${MONITOREO_SERVICE_URL:https://monitoreo-serviceindustrial.onrender.com}
              predicates:
                - Path=/api/v1/monitoreo/**

            - id: reportes-service
              uri: ${REPORTES_SERVICE_URL:https://reportes-serviceaustral.onrender.com}
              predicates:
                - Path=/api/v1/reportes/**

            - id: veterinario-service
              uri: ${VETERINARIO_SERVICE_URL:http://localhost:8085}
              predicates:
                - Path=/api/v1/veterinarios/**

          default-filters:
            - AddResponseHeader=X-Gateway, Service-Austral

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: INFO